name: SSH Action

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set up SSH
        run: |
          sudo mkdir -p ~/.ssh/
          sudo chmod 777 ~/.ssh
          sudo echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 700 ~/.ssh/id_rsa
          sudo ssh-keyscan ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: SSH conect machine
        run: |
          ssh admin@${{secrets.SSH_HOST}} 'bash' <<EOF 
          #!/bin/bash
          sudo su 
          echo "Iniciando Pull ..." >> /home/admin/logPullpw3.txt
          cd /var/www/pw3-final/gestor-financeiro
          date >> /home/admin/logPullpw3.txt
          git pull origin >> /home/admin/logPull.txt
          npm run build
          chown -R www-data:www-data /var/www/pw3-final
          php artisan optimize
          echo "Finalizado ..." >> /home/admin/logPullpw3.txt
          cat /home/admin/logPullpw3.txt | tail
          EOF
